command_onlyPlayers: "Sry, but only Players can use this command!"
command_tooFewArguments: "Sry, but you entered too few arguments!"
command_tooManyArguments: "Sry, but you entered too many arguments!"
command_usage_wpsgive: "/su <Player> <WPS> <Reason>"
command_usage_wpslist: "/wpslist"
command_usage_wpsclear: "/wpsclear <Player>"
command_usage_wpsshow: "/wpsshow [Player] (Only with permission wps.show.other)"
command_playerNotOnline: "Sry, but the player %PLAYER% is not online!"
command_noIntegerInput: "Sry, but your given input is not an integer!"
command_playerHasNoPoints: "Sry, but the player %PLAYER% does not have WPS"
player_pointsReceived: "&cDu hast eine Straftat begangen!/n&cMomentanes Wantedlevel: %WPS%/n&cGrund: %REASON%/n&cReporter: %REPORTER%"
player_playerReported: "Du hast erfolgreich %PLAYER% reported. Grund: %REASON%"
player_playerReported_broadcast: "Der Spieler %PLAYER% wurde von %REPORTER% für %REASON% gemeldet und hat nun %WPS% WPS"
command_noPermission: "Dir fehlen für diesen Befehl die Rechte: %PERMISSION%"
player_wpscleared: "Du hast erfolgreich die WPS von %PLAYER% gelöscht"
player_wpsclearedby: "Deine Akte wurde von %EXECUTOR% gelöscht!"
player_wpsclearedBroadcast: "Beamter %EXECUTOR% hat die Akte von %PLAYER% gelöscht. Dieser hatte %POINTS% WPS"
player_youarenotWanted: "Du wirst derzeit nicht gesucht."
player_notWanted: "%PLAYER% wird derzeit nicht gesucht!"
player_youareWanted: "Du wirst derzeit mit %WPS% WPS gesucht! Grund: %REASON%"
player_Wanted: "%PLAYER% wird derzeit mit %WPS% WPS gesucht! Grund: %REASON%"
player_noWantedPlayers: "Derzeit werden keine Spieler gesucht!"
player_WantedPlayersHeader: "Folgende Spieler werden gesucht  (%AMOUNT%):"
player_WantedPlayersFormat: "%PLAYER% | %WPS% | %REASON%"
command_IntegerOverOne: "Du musst eine Zahl größer 0 eingeben!"
